name: Generate New Tag

on:
  push:
    branches:
      - main

jobs:
  autotag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar nova tag automaticamente
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true         # Adiciona 'v' antes da versão (ex: v1.2.3)
          RELEASE_BRANCHES: main
