name: Generate .env

on:      
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  generate-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env File # Para que as variáveis a serem utilizadas adequadamente, elas devem ser armazenadas na aba Secrets da organização. Contate um membro do time DevOps.
        run: | 
          touch .env 
          echo "VAR1=${{ secrets.VAR1 }}" >> .env
          echo "VAR2=${{ secrets.VAR2 }}" >> .env
          echo "VAR3=${{ secrets.VAR3 }}" >> .env    

      - name: Upload .env Artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          include-hidden-files: true
          path: .env
          retention-days: 1
